name: tf2
channels:
  - conda-forge
  - defaults
dependencies:
  - graphviz
  - ipython
  - isort
  - joblib
  - jupyter
  - matplotlib
  - nbdime
  - nltk
  - numexpr
  - numpy
  - pandas
  - pillow
  - pip
  - py-xgboost
  - pylint
  - python
  - python-graphviz
  - scikit-learn
  - scipy
  - tqdm
  - wheel
  - widgetsnbextension
  - yapf
  - pip:
    - urlextract
